app/module_users/models.py
from sqlalchemy.sql import func
from app.extensions import db

import datetime
from passlib.hash import sha256_crypt
import sys

class User(db.Model):
  id = db.Column(db.Integer, primary_key=True)
  username = db.Column(db.VARCHAR(100), nullable=False, unique=True)
  password = db.Column(db.VARCHAR(200), nullable=False)
  email = db.Column(db.VARCHAR(200), nullable=False)
  permission = db.Column(db.Integer, server_default= "0")
  last_login = db.Column(db.DateTime(timezone=True),
                          server_default=func.now())

app/module_users/__init__.py
from flask import Blueprint

bp = Blueprint('users', __name__, template_folder='templates')

from . import routes, models, tools

tools.init()

app/module_users/routes.py
from flask import render_template, request, flash , session, redirect, url_for

from app.module_users import bp
from app.module_users.models import User
import app.module_users.tools as tools

from app.extensions import db

# 1: Kellner
# 2: Verwaltung
# 3: Admin


@bp.route('/login', methods=['POST', 'GET'])
def login():
    sessionUser = tools.getSessionUser()
    if sessionUser["permission"] > 0:
        return redirect(url_for('main.index'))

    else: 
        if request.method == 'POST':
            login = request.form
            userName = login['username']
            password = login['password']

            signedIn, permission, user= tools.verify(userName,password)
            if signedIn:
                session['logged_in'] = True
                session['permission'] = permission
                session['user_name'] = userName
                session['user_id'] = user.id
                return redirect(url_for('main.index'))

            else:
                flash('wrong password!')
                logout()
                return redirect(url_for('users.login'))
        else:
            
            return render_template('users/login.html')


@bp.route('/logout')
def logout():
    session['logged_in'] = False
    session['permission'] = 0
    session['user_name'] = None
    session['user_id'] = None
    return redirect(url_for('main.index'))


@bp.route('/addUser', methods=['POST','GET'])
def add_user():
    sessionUser = tools.getSessionUser()
    if sessionUser.get("permission") >= 3:
        if request.method == 'POST':
            login = request.form

            userName = login['username']
            password = login['password']
            email = login['email']
            permission = login['permission']
            if not tools.add_User(userName,password,permission,email):
                flash("Error creating User " + userName)

            return redirect(url_for('users.manageUsers'))

        elif request.method == 'GET':
            return redirect(url_for('users.manageUsers'))
    else:
        return redirect(url_for('main.index'))


@bp.route('/', methods=['GET'])
def manageUsers():
    sessionUser = tools.getSessionUser()
    if sessionUser.get("permission") >= 3:
        return render_template('users/manageUsers.html',users = tools.getUsers())
    else:
        return redirect(url_for('main.index'))

@bp.route('/deleteUser', methods=['POST'])
def deleteUser():
    sessionUser = tools.getSessionUser()
    if sessionUser.get("permission") >= 3:
        request_data = request.get_json()
        if 'id' in request_data:
            id = request_data["id"]
            tools.deleteUser(id)

        return redirect(url_for('user.manageUsers'))
    else:
        return redirect(url_for('user.login'))

app/module_users/templates/users/addUser.html
{% extends "layout.html" %}
{% block title %}Benutzerverwaltung{% endblock %}
{% block content %}
<div class='container'>
    <div class='card'>
        <div class='card-header'>
            <h1>Benutzer erstellen</h1>
        </div>
        <div class='card-body'>
            <form action="{{ url_for('user.add_user') }}" method="POST">
                <div class="login-screen">
                    <div class="control-group">
                        <a>Benutzername*</a><br>
                        <input type="text" class="login-field" value="" required placeholder="username" name="username">
                    </div>
                    <div class="control-group">
                        <a>Passwort*</a><br>
                        <input type="password" class="login-field" value="" required placeholder="password"
                            name="password">
                    </div>
                    <div class="control-group">
                        <a>email</a><br>
                        <input type="email" class="login-field" value="" placeholder="email" name="email">
                    </div>
                    <div class="control-group">
                        <a>Berechtigung*</a><br>
                        <input type="number" class="login-field" value="1" required step="1" min="1" max="3"
                            placeholder="" name="permission">

                    </div><br>
                    <input type="submit" value="Create" class="btn btn-primary btn-large btn-block">
                </div>
                <a>
                    <b>Berechtigungen:</b><br>
                    <a>1: Kellner</a><br>
                    <a>2: Verwaltung</a><br>
                    <a>3: Admin</a><br>
                </a>
            </form>
        </div>
    </div>
</div>

{% endblock %}
{% block style %}
{% endblock %}

app/module_users/templates/users/login.html
{% extends "layout.html" %}
{% block title %}Admin - Login{% endblock %}

{% block content %}

<div class='container'>
    <div class='card'>
        <div class='card-header'>
            <h1>Login</h1>
        </div>
        <div class='card-body'>
            <form action="{{ url_for('users.login') }}" method="POST">
                <div class="login">
                    <div class="login-screen">
                        <div class="login-form">
                            <div class="control-group">
                                <input type="text" class="login-field" value="" placeholder="username" name="username">
                            </div>
                            <div class="control-group">
                                <input type="password" class="login-field" value="" placeholder="password"
                                    name="password">
                            </div><br>
                            <input type="submit" value="Log in" class="btn btn-primary btn-large btn-block">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block style %}
{% endblock %}

app/module_users/templates/users/manageUsers.html
{% extends "layout.html" %}
{% block title %}Benutzerverwaltung{% endblock %}
{% block content %}


<div class='container'>
    <div class='card'>
        <div class='card-header'>
            <h1>Benutzer Verwalten</h1>
        </div>
        <div class='card-body'>
            <table class="table" style="width: auto">
                <tr class="table-header">
                    <th>ID</th>
                    <th>Benutzername</th>
                    <th>Rechte</th>
                    <th>Email</th>
                    <th>Last Login</th>
                    <th></th>
                </tr>
                {% for user in users %}
                    <tr>
                        <td><a>{{ user['id'] }}</a></td>
                        <td class="table-content"><a>{{ user['username'] }}</a></td>
                        <td class="table-content"><a>
                            {% if user['permission'] == 1 %}
                            Bediener
                            {% elif user['permission'] == 2 %}
                            Verwaltung
                            {% elif user['permission'] == 3 %}
                            Admin
                            {% else %}
                            UNBEKANNT
                            {% endif %} 
                        </a></td>
                        <td class="table-content">
                            {% if user['email'] %}
                                <a>{{ user['email'] }}</a>
                            {% else %}
                                <a>na</a>
                            {% endif %}
                        </td>
                        <td class="table-content"><a>{{ user['last_login'] }}</a></td>
                        <td>
                            <button class="btn btn-danger btn-block" onclick="deleteUser({{ user['id'] }}, '{{ user['username'] }}')">Löschen</button>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <div class='card'>
        <div class='card-header'>
            <h1>Benutzer erstellen</h1>
        </div>
        <div class='card-body'>
            <form action="{{ url_for('users.add_user') }}" method="POST">
                <div class="login-screen">
                    <div class="control-group">
                        <a>Benutzername*</a><br>
                        <input type="text" class="login-field" value="" required placeholder="username" name="username">
                    </div>
                    <div class="control-group">
                        <a>Passwort*</a><br>
                        <input type="password" class="login-field" value="" required placeholder="password"
                            name="password">
                    </div>
                    <div class="control-group">
                        <a>email</a><br>
                        <input type="email" class="login-field" value="" placeholder="email" name="email">
                    </div>
                    <div class="control-group">
                        <a>Berechtigung*</a><br>
                        <select id="permission" name="permission">
                            <option value=1>Bediener</option>
                            <option value=2>Verwaltung</option>
                            <option value=3>Admin</option>
                        </select>
                    </div><br>
                    <input type="submit" value="Create" class="btn btn-primary btn-large btn-block">
                </div>
            </form>
        </div>
    </div>


</div>



<script>
    function deleteUser(id, username){
        if (confirm("⚠🚨 Willst du den Benutzer \"" + username + "\" Löschen? 🚨⚠")) {
            fetch("{{url_for('users.deleteUser')}}", {
                method: "POST",
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify({'id':id})
            }).then(res => {
                alert("Benutzer \"" + username + "\" wurde gelöscht")
                console.log("Request complete! response:", res);
                location.reload()
            });
        }
    }
</script>
{% endblock %}
{% block style %}
    <style>
        .table-content{
            text-align: left;
            vertical-align: center;
            white-space: nowrap;
            padding-left: 5px;
        }
        .table-currency{
            text-align: right;
            vertical-align: center;
            white-space: nowrap;
            padding-left: 5px;
        }
    </style>
{% endblock %}