app/module_meals/models.py
from app.extensions  import db


class Restaurant(db.Model):
    __tablename__ = 'Restaurant'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(128), nullable=False)
    description = db.Column(db.String(128), nullable=False) # Changed to db.String to match VARCHAR
    phone = db.Column(db.String(32), nullable=True)
    website = db.Column(db.String(64), nullable=True)

    mealgroups = db.Relationship("Mealgroup", back_populates="restaurant", order_by='Mealgroup.number.asc()')


class Mealgroup(db.Model):
    __tablename__ = 'Mealgroup'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    number = db.Column(db.String(16), nullable=True)
    name = db.Column(db.String(128), nullable=False)
    description = db.Column(db.String(128), nullable=True)
    restaurant_id = db.Column(db.Integer, db.ForeignKey('Restaurant.id'), nullable=False)

    restaurant = db.Relationship("Restaurant", back_populates="mealgroups")
    meals = db.Relationship("Meal", back_populates="mealgroup")


class Meal(db.Model):
    __tablename__ = 'Meal'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    number = db.Column(db.String(16), nullable=True)
    name = db.Column(db.String(128), nullable=False)
    description = db.Column(db.String(128), nullable=True)
    mealgroup_id = db.Column(db.Integer, db.ForeignKey('Mealgroup.id'), nullable=False)
    price_1 = db.Column(db.Float, nullable=True)
    price_2 = db.Column(db.Float, nullable=True)
    price_3 = db.Column(db.Float, nullable=True)

    mealgroup = db.Relationship("Mealgroup", back_populates="meals")

app/module_orders/models.py
from app.extensions  import db

from app.module_meals.models import Meal
from sqlalchemy import func

class Order(db.Model):
    __tablename__ = 'Order'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    customer = db.Column(db.String(128), nullable=False)
    meal_id = db.Column(db.Integer, db.ForeignKey('Meal.id'), nullable=False)
    size = db.Column(db.String(32), nullable=False)
    notes = db.Column(db.String(128), nullable=True)
    price = db.Column(db.Float, nullable=False)
    payed = db.Column(db.Boolean, nullable=False, default=False)
    time_created = db.Column(db.DateTime(timezone=True), server_default=func.now())

    #meal = db.Relationship("Meal", back_populates="orders")
    

#    restaurant = db.Relationship("Restaurant", back_populates="mealgroups")

app/module_users/models.py
from sqlalchemy.sql import func
from app.extensions import db

import datetime
from passlib.hash import sha256_crypt
import sys

class User(db.Model):
  id = db.Column(db.Integer, primary_key=True)
  username = db.Column(db.VARCHAR(100), nullable=False, unique=True)
  password = db.Column(db.VARCHAR(200), nullable=False)
  email = db.Column(db.VARCHAR(200), nullable=False)
  permission = db.Column(db.Integer, server_default= "0")
  last_login = db.Column(db.DateTime(timezone=True),
                          server_default=func.now())

app/__init__.py
from flask import Flask, render_template
from flask_migrate import Migrate
import os

from app.config import Config
from app.extensions import db

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    with app.app_context():
        # Initialize Flask extensions here

        db.init_app(app)
        
        basedir = os.path.abspath(os.path.dirname(__file__))
        MIGRATION_DIR = os.path.join(basedir, 'data', 'migrations')  
        
        migrate = Migrate(app, db, directory=MIGRATION_DIR)
        
        # Register blueprints here
        import app.module_main as main
        app.register_blueprint(main.bp)
        import app.module_users as users
        app.register_blueprint(users.bp, url_prefix="/users")
        import app.module_meals as meals
        app.register_blueprint(meals.bp, url_prefix="/meals")
        import app.module_orders as orders
        app.register_blueprint(orders.bp, url_prefix="/orders")

        db.create_all()
        meals.tools.loadRestaurants()

    @app.route('/test')
    def test():
        return render_template('test.html')


    return app

app/module_main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, template_folder='templates')

from . import routes

app/module_main/routes.py
from flask import render_template

from app.module_main import bp

@bp.route('/')
def index():
    return render_template('index.html')

app/module_meals/__init__.py
from flask import Blueprint

bp = Blueprint('meals', __name__, template_folder='templates')

from . import routes, models, tools

app/module_meals/routes.py
from flask import render_template

from app.module_meals import bp
from app.module_meals.models import Restaurant, Mealgroup, Meal

from app.extensions import db

@bp.route('/')
def index():
    restaurants = db.session.query(Restaurant)
    return render_template('meals/index.html', restaurants=restaurants)

app/module_orders/__init__.py
from flask import Blueprint

bp = Blueprint('orders', __name__, template_folder='templates')

from . import routes, models

app/module_orders/routes.py
from flask import render_template, request, redirect, url_for

from app.module_orders import bp
from app.module_orders.models import Order
from app.module_meals.models import Meal

from app.extensions import db

@bp.route('/')
def editOrder():
    meal_id = request.args.get('meal_id')
    meal = db.session.scalar(db.select(Meal).filter_by(id = meal_id))
    if meal:
        return render_template('orders/editOrder.html', meal=meal)
    else:
        return redirect(url_for('meals.index'))

app/module_users/__init__.py
from flask import Blueprint

bp = Blueprint('users', __name__, template_folder='templates')

from . import routes, models, tools

tools.init()

app/module_users/routes.py
from flask import render_template, request, flash , session, redirect, url_for

from app.module_users import bp
from app.module_users.models import User
import app.module_users.tools as tools

from app.extensions import db

# 1: Kellner
# 2: Verwaltung
# 3: Admin


@bp.route('/login', methods=['POST', 'GET'])
def login():
    sessionUser = tools.getSessionUser()
    if sessionUser["permission"] > 0:
        return redirect(url_for('main.index'))

    else: 
        if request.method == 'POST':
            login = request.form
            userName = login['username']
            password = login['password']

            signedIn, permission, user= tools.verify(userName,password)
            if signedIn:
                session['logged_in'] = True
                session['permission'] = permission
                session['user_name'] = userName
                session['user_id'] = user.id
                return redirect(url_for('main.index'))

            else:
                flash('wrong password!')
                logout()
                return redirect(url_for('users.login'))
        else:
            
            return render_template('users/login.html')


@bp.route('/logout')
def logout():
    session['logged_in'] = False
    session['permission'] = 0
    session['user_name'] = None
    session['user_id'] = None
    return redirect(url_for('main.index'))


@bp.route('/addUser', methods=['POST','GET'])
def add_user():
    sessionUser = tools.getSessionUser()
    if sessionUser.get("permission") >= 3:
        if request.method == 'POST':
            login = request.form

            userName = login['username']
            password = login['password']
            email = login['email']
            permission = login['permission']
            if not tools.add_User(userName,password,permission,email):
                flash("Error creating User " + userName)

            return redirect(url_for('users.manageUsers'))

        elif request.method == 'GET':
            return redirect(url_for('users.manageUsers'))
    else:
        return redirect(url_for('main.index'))


@bp.route('/', methods=['GET'])
def manageUsers():
    sessionUser = tools.getSessionUser()
    if sessionUser.get("permission") >= 3:
        return render_template('users/manageUsers.html',users = tools.getUsers())
    else:
        return redirect(url_for('main.index'))

@bp.route('/deleteUser', methods=['POST'])
def deleteUser():
    sessionUser = tools.getSessionUser()
    if sessionUser.get("permission") >= 3:
        request_data = request.get_json()
        if 'id' in request_data:
            id = request_data["id"]
            tools.deleteUser(id)

        return redirect(url_for('user.manageUsers'))
    else:
        return redirect(url_for('user.login'))

app/templates/layout.html
<!DOCTYPE html>
<html lang="de" data-bs-theme="light">
<head>
    <link rel="icon" type="image/svg+xml" href="/static/images/kebab.svg">
    <!--<link rel="icon" type="image/png" href="/assets/images/favicon.png">-->
    <meta charset='UTF-8'>
    <title>{% block title %}SammelBestellApp{% endblock %}</title>
  
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="color-scheme" content="light">  
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"></script>

    <link href="/static/css/style.css" rel="stylesheet">

    {% block header %}{% endblock %}

</head>

<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('main.index')}}">
                <img src="/static/images/kebab.svg" width="30" height="30" class="d-inline-block align-top" style="color:var(--bs-secondary)" alt="">
                
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Bestellen</a>
                    </li>

                    {% if session['permission']|default(0, true) >= 1 %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.logout')}}">Logout</a>
                    </li>
                    {% endif %}

                    {% if session['permission']|default(0, true) <= 0 %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.login')}}">Login</a>
                    </li>
                    {% endif %}
                    {% if session['permission']|default(0, true) >= 2 %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Verwalten
                        </a>
                        <ul class="dropdown-menu">
                            {% if session['permission'] >= 3 %}
                            <li><a class="dropdown-item" href="{{ url_for('users.manageUsers') }}">Benutzer</a></li>
                            {% endif %}
                        </ul>
                    </li>
                    {% endif %}


    
                </ul>
            </div>
        </div>
    </nav>

    <div class="content">
        {% block content%}
        {% endblock %}
    </div>

     {% block script %}
    <script>
    </script>
    {% endblock %}

    {% block style %}
    <style>
    </style>
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

app/templates/test.html
{% extends 'layout.html' %}

{% block content %}
<div id="content" class="container-fluid content">
    <div class="row"> <!-- Hier kannst du weitere Inhalte hinzufügen -->
        <!-- Plan Sequence -->
        <div class="col-md-12 d-flex flex-column">
            <div class="card mt-2 mb-2">
                <h5 class="card-header">Essensgruppe</h5>
                <div class="card-body">
                    <table class="table">
                        <tbody>
                            <tr>
                                <td>1a</td>
                                <td>
                                    <b>Hawaii</b><br>
                                    Tomatensauce, Käse, Schinken, Annanas
                                    <br>5.00€ - 6.00€ - 12.00€
                                </td>
                                <td>
                                    <button type="button" class="btn btn-primary">Bestellen</button>
                                </td>
                            </tr>
                            <tr>
                                <td>1a</td>
                                <td>
                                    <b>Hawaii</b><br>
                                    Tomatensauce, Käse, Schinken, Annanas
                                    <br>5.00€ - 6.00€ - 12.00€
                                </td>
                                <td>
                                    <button type="button" class="btn btn-primary">Bestellen</button>
                                </td>
                            </tr>
                            <tr>
                                <td>1a</td>
                                <td>
                                    <b>Hawaii</b><br>
                                    Tomatensauce, Käse, Schinken, Annanas
                                    <br>5.00€ - 6.00€ - 12.00€
                                </td>
                                <td>
                                    <button type="button" class="btn btn-primary">Bestellen</button>
                                </td>
                            </tr>
                            <tr>
                                <td>1a</td>
                                <td>
                                    <b>Hawaii</b><br>
                                    Tomatensauce, Käse, Schinken, Annanas
                                    <br>5.00€ - 6.00€ - 12.00€
                                </td>
                                <td>
                                    <button type="button" class="btn btn-primary">Bestellen</button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}